---

 - name: Add repository
    yum_repository:
     name: zabbix
     description: Zabbix repo
     baseurl: http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/
     gpgcheck: no
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"    

  - name: Add repository
    yum_repository:
     name: zabbix
     description: Zabbix repo
     baseurl: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/
     gpgcheck: no 
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Yum install Zabbix agent
    yum: name=zabbix-agent state=latest
    when: ansible_distribution == "CentOS"
